condorman/urls.py
from django.conf.urls.defaults import patterns, include, url
from condorman.models import CondorUser

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('condorman.views',
    url(r'^$', 'index'),
    url(r'^test$', 'test'),
    url(r'^add/$', 'add'),
    url(r'^modify/$', 'add'),
    url(r'^process/$', 'process'),
    url(r'^log/$', 'log'),
)

urlpatterns += patterns('',
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

mysite/urls.py
from django.conf.urls.defaults import include, url, patterns
from django.conf.urls.defaults import handler404, handler500
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # hack to use admin widgets
    url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    #
#    url(r'^polls/', include('polls.urls')),
    url(r'^condorman/', include('condorman.urls')),
    url(r'media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    )

                     

condorman/models.py
from django.db import models
from datetime import datetime
from reversion.helpers import patch_admin


# Create your models here.
class CondorUser(models.Model):
    def __unicode__(self):
        return self.username
    class Meta:
        ordering = ['username']
    username = models.CharField(max_length=255, unique=True)
    isAdmin = models.BooleanField()

class PrioFactor(models.Model):
    def __unicode__(self):
        return "%s" % self.factor
    
    user = models.ForeignKey(CondorUser)
    factor = models.FloatField(max_length=200)
    start_date = models.DateTimeField('Start Date')
    end_date = models.DateTimeField('End Date')

    def expired(self):
        return (datetime.now() > self.end_date)

class LogAction(models.Model):
    def __unicode__(self):
        return '%s, %s, %s' % (self.action_date, self.authuser, self.action)

    authuser = models.CharField(max_length=255)
    action = models.CharField(max_length=255)
    action_date = models.DateTimeField('Action Date')
    

condorman/forms.py
from django import forms
from condorman.models import CondorUser, PrioFactor
from condorman.util import getUserList
from django.forms import forms, ModelForm
from django.contrib.admin import widgets

class PrioFactorForm(ModelForm):
    class Meta:
        model = PrioFactor

    def __init__(self, *args, **kwargs):
        super(PrioFactorForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget = widgets.AdminDateWidget()
        self.fields['end_date'].widget = widgets.AdminDateWidget()
        self.fields['user'].queryset = getUserList().order_by('username')

    def clean(self):
        cleaned_data = super(PrioFactorForm, self).clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if (end_date <= start_date):
            raise forms.ValidationError("end_date must be "
                                        "later than start_date")

        return cleaned_data

condorman/views.py
# Create your views here.
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from condorman.models import CondorUser, PrioFactor, LogAction
from condorman.forms import PrioFactorForm
from condorman.util import getUserList
from django.http import HttpResponse, HttpResponseRedirect
import md5
from datetime import datetime
from condorman.admin import PrioFactorAdmin

# to do: build backend to auth users based on REMOTE_USER
#   build unauth pages

def log(request):
    logtable = LogAction.objects.all()
    return HttpResponse(logtable)

def test(request):
    userList = getUserList()
    user = request.META['REMOTE_USER']
    return render_to_response('condorman/testindex.html', {'userList': userList, 'remote_user': user,
                                                       'userHash':  md5.new(user).hexdigest()[0:30],
                                                       'can_add': request.user.has_perm('condorman.add_priofactor'),
                                                       'can_del': request.user.has_perm('condorman.delete_priofactor')})
    
def index(request):
    userList = getUserList()
    user = request.META['REMOTE_USER']
    return render_to_response('condorman/index.html', {'userList': userList, 'remote_user': user,
                                                       'userHash':  md5.new(user).hexdigest()[0:30],
                                                       'can_add': request.user.has_perm('condorman.add_priofactor'),
                                                       'can_del': request.user.has_perm('condorman.delete_priofactor')})

def add(request):
    if not request.user.has_perm('condorman.add_priofactor'):
        return HttpResponseRedirect(reverse('condorman.views.index'))

    userList = getUserList()
    a = PrioFactorForm()
    return render_to_response('condorman/add.html',
                              {'form': a, 'userList': userList},
                              )

def log_this(authuser, action):
    l = LogAction(authuser=authuser, action=action, action_date=datetime.now())
    l.save()
    
def process(request):
    if request.method == 'POST' and request.POST.keys():
        if request.POST.has_key('remove'):
            if not request.user.has_perm('condorman.delete_priofactor'):
                return HttpResponseRedirect(reverse('condorman.views.index'))
            for item in request.POST.getlist('remove'):
                pf = PrioFactor.objects.get(id=item)
                pf.delete()

        else:
            # add lines
            if not request.user.has_perm('condorman.add_priofactor'):
                return HttpResponseRedirect(reverse('condorman.views.index'))
            form = PrioFactorForm(request.POST)
            if not form.is_valid():
                userList = getUserList()
                return render_to_response('condorman/add.html',
                                          {'form': form,
                                           'userList': userList},
                                          context_instance=RequestContext(request)
                                          )
            else:
                data = form.cleaned_data
                p =  PrioFactor(user=data.get('user'),
                                factor=data.get('factor'),
                                start_date=data.get('start_date'),
                                end_date= data.get('end_date'))
                
                p.save()
                log_this(request.user, 'add')

    return HttpResponseRedirect(reverse('condorman.views.index'))

templates/condorman/add.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us" >
<head>
<title>Test</title>

<head>
<link rel="stylesheet" type="text/css" href="/media/css/forms.css"/>
<link rel="stylesheet" type="text/css" href="/media/css/base.css"/>
<link rel="stylesheet" type="text/css" href="/media/css/widgets.css" />
<link rel="stylesheet" type="text/css" href="/media/css/global.css"/>
<script type="text/javascript" src="/my_admin/jsi18n/"></script>
<script type="text/javascript" src="/media/js/core.js"></script>
{{ form.media }}
</head>

<body>

<h1>Add a new priority</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/condorman/process/" method="post">
{% csrf_token %}

{{ form.as_p }} 
<input type="submit" value="Submit" />
</form>

templates/condorman/index.html
<head>
<style type="text/css" title="currentStyle">
@import "/media/css/jquery.dataTables.css";
</style>

<script type="text/javascript" src="/media/js/jquery.js"/></script>
<script type="text/javascript" src="/media/js/jquery.dataTables.js"/></script>
<script type="text/javascript" src="/media/js/dataTables-bnh.js"/></script>
<script type="text/javascript" type="utf-8"/>
   $(document).ready(function() {
       $('#priotable').dataTable( {
       "aoColumns": [null, null,
          { "sType": "monthYear" },
	  { "sType": "monthYear" },
	  {% if can_del %}null{% endif %}],
          "bPaginate": false,
	  "bAutoWidth": false,
	  } );
   } );
</script>
</head>

<body>

<h1>Table of user priorities</h1>

{% if userList %}
<form action="/condorman/process/" method="post">
<table id="priotable" border="2"  cellspacing="1">
<thead><tr>
<th>User</th><th>Priority Factor</th><th>Start Date</th><th>End Date</th>
{% if can_del %}<th>Delete?</th>{% endif %} 
</tr></thead>


<tbody>
{% for user in userList %}
{% for pf in user.priofactor_set.all %}
<tr>
  <td> {% if forloop.first %} {{ user }} {% endif %} </td>
  <td><font {% if pf.expired %} color="red" {% endif %} >
      {{ pf.factor }} </font></td>
  <td><font {% if pf.expired %} color="red" {% endif %} > 
      {{ pf.start_date|date:"F j, Y" }} </font></td>
  <td><font {% if pf.expired %} color="red" {% endif %} >
      {{ pf.end_date|date:"F j, Y" }} </font></td>
{% if can_del %}<td><input type="checkbox" name="remove" id="pf{{ forloop.counter }}" value="{{ pf.id }}" /> </td>{% endif %}
</tr>
{% endfor %}
{% endfor %}
</tbody>


</table>
<br>
<input type="submit" value="Submit" />
</form>
{% endif %}
<p>
{% if can_add %} <a href="/condorman/add">Add a new line</a> {% endif %}

<br><br><br>
<small>Authenticated as: <font color="blue">{{ remote_user }}
{{ userHash }}</font></small>
<br>
</body>

templates/condorman/input.html
<h1> Input thingy </h1>

templates/condorman/testindex.html
<head>
<style type="text/css" title="currentStyle">
@import "/media/css/jquery.dataTables.css";
</style>

<script type="text/javascript" src="/media/js/jquery.js"/></script>
<script type="text/javascript" src="/media/js/jquery.dataTables.js"/></script>
<script type="text/javascript" src="/media/js/dataTables-bnh.js"/></script>
<script type="text/javascript" type="utf-8"/>
   $(document).ready(function() {
       $('#priotable').dataTable( {
       "aoColumns": [null, null,
          { "sType": "monthYear" },
	  { "sType": "monthYear" },
	  null],
          "bPaginate": false,
	  "bAutoWidth": false,
	  } );
   } );
</script>
</head>

<body>

<h1>Table of user priorities</h1>

{% if userList %}
<form action="/condorman/process/" method="post">
<table id="priotable" border="2"  cellspacing="1">
<thead><tr>
<th>User</th><th>Priority Factor</th><th>Start Date</th><th>End Date</th>
{% if can_del %}<th>Delete?</th>{% endif %}
</tr></thead>
<tbody>
{% for user in userList %}
{% for pf in user.priofactor_set.all %}

<tr>
    <td> {% if forloop.first %} {{ user }} {% endif %} </td> 
    <td><font {% if pf.expired %} color="red" {% endif %} >
    {{ pf.factor }} </font></td>
    <td><font {% if pf.expired %} color="red" {% endif %} >
    {{ pf.start_date|date:"F j, Y" }} </font></td>
    <td><font {% if pf.expired %} color="red" {% endif %} >
    {{ pf.end_date|date:"F j, Y" }} </font></td>
    {% if can_del %}<td> <input type="checkbox" name="remove" id="pf{{ forloop.counter }}" value="{{ pf.id }}" /></td>  {% endif %}
</tr>
{% endfor %}
{% endfor %}
</tbody>
</table>
<br>
<input type="submit" value="Submit" />
</form>
{% endif %}
<p>
{% if can_add %} <a href="/condorman/add">Add a new line</a> {% endif %}

<br><br><br>
<small>Authenticated as: <font color="blue">{{ remote_user }}
{{ userHash }}</font></small>
<br>
</body>

templates/results.html
<h1>{{ poll.question }}</h1>